env:
  browser: false
  node: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/prefer-default-export: 0
  import/extensions: 0
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
